server.port=8081

# Data Koneksi dari TiDB Cloud kamu
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/eventhub_baru?sslMode=VERIFY_IDENTITY
spring.datasource.username=2fmcBPWsm8hFBgk.root
spring.datasource.password=joxJtyx0syZ3bxyj

# Driver dan Pengaturan Database
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Pengaturan Static File (dari file lama kamu)
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**